// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  project: dynamic(() => import("./Project")),
  slider_gallery: dynamic(() => import("./SliderGallery")),
};
